my_list=[]
#_my_list,MyList,myList
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
print(my_list)
my_list.insert(1,15)
print(my_list)
my_list.extend([50,60,70])
print(my_list)
my_list.remove(70)
print(my_list)
my_list.sort()
print(my_list)
my_list.reverse()
print(my_list)
my_list.pop()
print(my_list)
index_30=my_list.index(30)
print("index of 30:",index_30)
my_list.clear()
print(my_list)

